### ISSUE TITLE
Can't compile pquery

### ISSUE THREAD

**Issue by Qwentor** [Percona-QA/pquery#13]
cmake works perfect, but when I try to run make I got this:

`Scanning dependencies of target inih++

[ 16%] Building C object src/third_party/inih++/lib/CMakeFiles/inih++.dir/ini.c.o

<command-line>:0:0: error: "FORK" redefined

<command-line>:0:0: note: this is the location of the previous definition

src/third_party/inih++/lib/CMakeFiles/inih++.dir/build.make:54: recipe for target 'src/third_party/inih++/lib/CMakeFiles/inih++.dir/ini.c.o' failed

make[2]: *** [src/third_party/inih++/lib/CMakeFiles/inih++.dir/ini.c.o] Error 1

CMakeFiles/Makefile2:157: recipe for target 'src/third_party/inih++/lib/CMakeFiles/inih++.dir/all' failed

make[1]: *** [src/third_party/inih++/lib/CMakeFiles/inih++.dir/all] Error 2

Makefile:137: recipe for target 'all' failed

make: *** [all] Error 2`

Debian Jessie

gcc (Debian 4.9.2-10) 4.9.2

cmake version 3.0.2

**Comment by RoelVdP** [comment]
@Qwentor btw, you can also use the pre-compiled binaries in percona-qa;
```
$ cd ~
$ git branch https://github.com/Percona-QA/percona-qa.git 
$ cd ~/percona-qa/pquery/
$ ls pquery2*
```
I am uploading new ones with latest fixes today.

**Comment by abychko** [comment]
@Qwentor please add some details:
1 - mysql flavour with version - i.e. mysql, mariadb, PerconaServer, etc
2 - exact cmake command used to configure the sources

**Comment by RoelVdP** [comment]
Also don't forget to run `./clean-tree.sh` first

**Comment by RoelVdP** [comment]
Binaries pquery2-ps, pquery2-ms and pquery2-pxc were pushed to percona-qa, instructions above.

**Comment by RoelVdP** [comment]
No input provided, closing
